#!/bin/bash

workdir=$(dirname `realpath $0`)
root=`realpath ${workdir}/..`
postdir=${workdir}/_posts

echo 'root = '${root}
echo 'workdir ='${workdir}

mkdir -p ${postdir}
seq 2015 `date +%Y` | xargs -I% mv $root/% $postdir

jekyll build --source $workdir --destination $root/docs
ls ${postdir} | xargs -I% mv $postdir/% $root
